name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Wait for 2 minutes to complete deploy
        run: sleep 120

  run-tests:
    needs: deploy-stage
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Change to tests directory
      run: cd tests
      
    - name: Execute UI tests
      run: dotnet test
      working-directory: tests
        
  deploy-prod:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_PROD }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
