name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract Commit SHA
        id: extract_sha
        run: echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
      - name: Trigger Render Deploy Hook
        run: |
          DEPLOY_HOOK_URL=${{ secrets.DEPLOY_HOOK_URL }}
          COMMIT_SHA=${{ steps.extract_sha.outputs.commit_sha }}
          curl -X POST "$DEPLOY_HOOK_URL&ref=$COMMIT_SHA"
      - name: Wait for 2 minutes to complete deploy
        run: sleep 120
        
  deploy-prod:
    needs: deploy-stage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_PROD }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
