name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Wait for 2 minutes to complete deploy
        run: sleep 120
        
  deploy-prod:
    needs: deploy-stage
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Wait for 2 minutes to complete deploy
        run: sleep 120
